project:
  type: default
  output-dir: _output
  render:
    - presentation.qmd

title: "[簡報標題]"
subtitle: "[副標題]"
author: "[作者]"
date: "[日期]"

format:
  beamer:
    pdf-engine: xelatex
    include-in-header:
      - {{FW}}/assets/templates/presentation/preamble.tex
    theme: metropolis
    colortheme: default
    aspectratio: 169
    navigation: empty
    colorlinks: true
    linkcolor: black
    urlcolor: blue
    citecolor: black

bibliography: references.bib
csl: {{FW}}/assets/chicago-fullnote-bibliography.csl
lang: zh-Hant
